In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
train = pd.read_csv("D:/DATASETS/FINANCIAL STRESS PREDICTOR/train.csv")
test = pd.read_csv("D:/DATASETS/FINANCIAL STRESS PREDICTOR/test.csv")

In [3]:
train.head()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal,liquidity_stress_next_30d,ID
0,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,8,58372.55,...,0.00,0.0,12488.72,11404.86,12943.70,14157.61,13202.11,4336.98,1,ID_C1DF84C4D2
1,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,5191.14,4.0,13677.61,2781.25,5897.59,5416.23,11062.23,4849.68,0,ID_CB8B764D76
2,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,12,41262.86,...,0.00,0.0,7271.09,5364.41,9023.13,13001.02,17107.92,15174.32,1,ID_D40D58FC67
3,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,10,8738.58,...,8965.63,3.0,14331.10,33465.26,2973.45,3577.07,18990.91,8488.26,0,ID_CFD8F26581
4,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,2,3654.68,...,0.00,0.0,5602.75,8497.49,26252.75,7618.93,9290.65,4214.71,0,ID_20EB501231

In [4]:
test.head()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_total_value,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal,ID
0,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,0.00,0.00,0.0,7272.55,9390.57,17239.77,12989.74,11233.97,16461.21,ID_ED91AC7A28
1,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,14,89420.67,...,99816.47,11869.21,2.0,9541.97,2966.31,8673.89,11626.41,4163.57,4978.28,ID_29975A9C7E
2,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,27491.22,7761.80,5.0,3182.31,10784.62,5614.67,6834.96,10062.58,2954.87,ID_F59CE25650
3,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,0,0.00,...,25776.34,13914.75,3.0,15452.29,32939.01,3682.57,8570.83,8688.00,9627.55,ID_E875F68D1A
4,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,0,0.00,...,57119.91,12371.51,5.0,11052.63,7294.56,32332.63,4043.43,11680.77,7326.46,ID_2902B1C0D0

In [5]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Columns: 184 entries, arpu to ID
dtypes: float64(134), int64(44), str(6)
memory usage: 56.2 MB

In [6]:
train.isnull()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal,liquidity_stress_next_30d,ID
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
train.isnull().sum()

arpu                         0
age                          0
gender                       0
region                       0
smartphone                   0
                            ..
m4_daily_avg_bal             0
m5_daily_avg_bal             0
m6_daily_avg_bal             0
liquidity_stress_next_30d    0
ID                           0
Length: 184, dtype: int64

In [8]:
train.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
39995    False
39996    False
39997    False
39998    False
39999    False
Length: 40000, dtype: bool

In [9]:
train.duplicated().sum()

np.int64(0)

In [10]:
train["liquidity_stress_next_30d"].value_counts()

liquidity_stress_next_30d
0    34000
1     6000
Name: count, dtype: int64

In [11]:
train["liquidity_stress_next_30d"].value_counts(normalize=True) * 100

liquidity_stress_next_30d
0    85.0
1    15.0
Name: proportion, dtype: float64

In [12]:
TARGET = "liquidity_stress_next_30d"
y = train[TARGET]
y.head()

0    1
1    0
2    1
3    0
4    0
Name: liquidity_stress_next_30d, dtype: int64

In [13]:
y.dtype, y.nunique()

(dtype('int64'), 2)

In [14]:
y.value_counts()

liquidity_stress_next_30d
0    34000
1     6000
Name: count, dtype: int64

In [15]:
ID_COL = "ID"

feature_cols = [
    c for c in train.columns
    if c not in [ID_COL, TARGET]
]

print("Number of features:", len(feature_cols))

Number of features: 182

In [16]:
X = train[feature_cols]

X.head()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_volume,m6_withdraw_total_value,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal
0,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,8,58372.55,...,0,0.00,0.00,0.0,12488.72,11404.86,12943.70,14157.61,13202.11,4336.98
1,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,9,90423.40,5191.14,4.0,13677.61,2781.25,5897.59,5416.23,11062.23,4849.68
2,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,12,41262.86,...,0,0.00,0.00,0.0,7271.09,5364.41,9023.13,13001.02,17107.92,15174.32
3,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,10,8738.58,...,11,98268.75,8965.63,3.0,14331.10,33465.26,2973.45,3577.07,18990.91,8488.26
4,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,2,3654.68,...,0,0.00,0.00,0.0,5602.75,8497.49,26252.75,7618.93,9290.65,4214.71

In [17]:
cat_cols = X.select_dtypes(include="object").columns.tolist()

print("Number of categorical features:", len(cat_cols))
print(cat_cols)

Number of categorical features: 5
['gender', 'region', 'smartphone', 'segment', 'earning_pattern']

C:\Users\Eis7\AppData\Local\Temp\ipykernel_9136\1261099881.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include="object").columns.tolist()

In [18]:
for col in cat_cols:
    print(f"\n{col}:")
    print(X[col].unique())

gender:
<StringArray>
['F', 'M']
Length: 2, dtype: str

region:
<StringArray>
[              'Central Zone',         'Northern Highlands',
      'Lake Zone (Northwest)', 'Coastal & Eastern Corridor',
         'Southern Highlands',                   'Islander',
               'Western Zone']
Length: 7, dtype: str

smartphone:
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

segment:
<StringArray>
['MVC', 'LVC', 'HVC']
Length: 3, dtype: str

earning_pattern:
<StringArray>
['Monthly Earner', 'Weekly Earner', 'Irregular Earner']
Length: 3, dtype: str

In [19]:
X_encoded = X.copy()

X_encoded.head()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_volume,m6_withdraw_total_value,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal
0,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,8,58372.55,...,0,0.00,0.00,0.0,12488.72,11404.86,12943.70,14157.61,13202.11,4336.98
1,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,9,90423.40,5191.14,4.0,13677.61,2781.25,5897.59,5416.23,11062.23,4849.68
2,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,12,41262.86,...,0,0.00,0.00,0.0,7271.09,5364.41,9023.13,13001.02,17107.92,15174.32
3,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,10,8738.58,...,11,98268.75,8965.63,3.0,14331.10,33465.26,2973.45,3577.07,18990.91,8488.26
4,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,2,3654.68,...,0,0.00,0.00,0.0,5602.75,8497.49,26252.75,7618.93,9290.65,4214.71

In [20]:
X_encoded = pd.get_dummies(
    X_encoded,
    columns=cat_cols,
    drop_first=True
)

print("Features after encoding:", X_encoded.shape[1])

Features after encoding: 189

In [21]:
X_encoded.dtypes.value_counts()

float64    134
int64       43
bool        12
Name: count, dtype: int64

In [22]:
X_encoded.isnull().sum().sum()

np.int64(0)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("y_train:", y_train.shape)
print("y_val:", y_val.shape)

X_train: (32000, 189)
X_val: (8000, 189)
y_train: (32000,)
y_val: (8000,)

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

print("X_train_scaled:", X_train_scaled.shape)
print("X_val_scaled:", X_val_scaled.shape)

X_train_scaled: (32000, 189)
X_val_scaled: (8000, 189)

In [25]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=100,
    class_weight="balanced",
    solver="liblinear"
)

model.fit(X_train_scaled, y_train)

print("Model training completed!")

Model training completed!

In [26]:
val_pred_prob = model.predict_proba(X_val_scaled)[:, 1]

print(val_pred_prob[:10])

[0.37989242 0.05355732 0.77078879 0.44734794 0.52814447 0.36998911
 0.10859922 0.70464795 0.48004258 0.69307449]

In [27]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_val, val_pred_prob)

print("Validation ROC-AUC:", roc_auc)

Validation ROC-AUC: 0.7531676470588237

In [28]:
val_pred_label = (val_pred_prob >= 0.5).astype(int)

print(val_pred_label[:20])

[0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 0]

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_val, val_pred_label))

              precision    recall  f1-score   support

           0       0.93      0.69      0.79      6800
           1       0.28      0.70      0.40      1200

    accuracy                           0.69      8000
   macro avg       0.61      0.69      0.60      8000
weighted avg       0.83      0.69      0.73      8000

In [30]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_val, val_pred_label)

print(cm)

[[4680 2120]
 [ 360  840]]

In [31]:
from sklearn.inspection import permutation_importance

In [32]:
result = permutation_importance(
    model,
    X_val_scaled,
    y_val,
    n_repeats=3,
    random_state=42,
    n_jobs=-1
)

print("Permutation importance completed!")

Permutation importance completed!

In [33]:
importances = pd.Series(
    result.importances_mean,
    index=X_encoded.columns
)

print(importances.sort_values(ascending=False).head(10))

m5_daily_avg_bal              0.041167
m4_daily_avg_bal              0.040708
m6_daily_avg_bal              0.040375
segment_MVC                   0.028958
m2_withdraw_volume            0.018167
m1_withdraw_volume            0.017833
m3_withdraw_volume            0.017667
m1_received_highest_amount    0.014375
m6_deposit_volume             0.012167
m3_mm_send_volume             0.011667
dtype: float64

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

In [36]:
rf_model.fit(X_train, y_train)

print("Random Forest training completed!")

Random Forest training completed!

In [37]:
rf_pred_prob = rf_model.predict_proba(X_val)[:, 1]

print(rf_pred_prob[:10])

[0.07 0.15 0.29 0.06 0.15 0.1  0.07 0.18 0.21 0.24]

In [38]:
from sklearn.metrics import roc_auc_score

rf_roc_auc = roc_auc_score(y_val, rf_pred_prob)

print("Random Forest Validation ROC-AUC:", rf_roc_auc)

Random Forest Validation ROC-AUC: 0.7812919730392157

In [39]:
rf_pred_label = (rf_pred_prob >= 0.5).astype(int)

print(rf_pred_label[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [40]:
from sklearn.metrics import classification_report

print(classification_report(y_val, rf_pred_label))

              precision    recall  f1-score   support

           0       0.86      1.00      0.92      6800
           1       0.92      0.09      0.16      1200

    accuracy                           0.86      8000
   macro avg       0.89      0.54      0.54      8000
weighted avg       0.87      0.86      0.81      8000

In [41]:
from sklearn.metrics import confusion_matrix

rf_cm = confusion_matrix(y_val, rf_pred_label)

print(rf_cm)

[[6791    9]
 [1097  103]]

In [42]:
rf_pred_label_03 = (rf_pred_prob >= 0.3).astype(int)

print(classification_report(y_val, rf_pred_label_03))

              precision    recall  f1-score   support

           0       0.88      0.97      0.93      6800
           1       0.64      0.27      0.38      1200

    accuracy                           0.87      8000
   macro avg       0.76      0.62      0.65      8000
weighted avg       0.85      0.87      0.84      8000

In [43]:
rf_pred_label_02 = (rf_pred_prob >= 0.2).astype(int)

print(classification_report(y_val, rf_pred_label_02))

              precision    recall  f1-score   support

           0       0.91      0.87      0.89      6800
           1       0.41      0.51      0.45      1200

    accuracy                           0.82      8000
   macro avg       0.66      0.69      0.67      8000
weighted avg       0.83      0.82      0.82      8000

In [44]:
from sklearn.metrics import precision_score, recall_score, f1_score

thresholds = [0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]

for threshold in thresholds:
    pred = (rf_pred_prob >= threshold).astype(int)

    precision = precision_score(y_val, pred)
    recall = recall_score(y_val, pred)
    f1 = f1_score(y_val, pred)

    print(
        f"Threshold: {threshold:.2f} | "
        f"Precision: {precision:.2f} | "
        f"Recall: {recall:.2f} | "
        f"F1: {f1:.2f}"
    )

Threshold: 0.10 | Precision: 0.21 | Recall: 0.89 | F1: 0.34
Threshold: 0.15 | Precision: 0.30 | Recall: 0.71 | F1: 0.42
Threshold: 0.20 | Precision: 0.41 | Recall: 0.51 | F1: 0.45
Threshold: 0.25 | Precision: 0.53 | Recall: 0.37 | F1: 0.44
Threshold: 0.30 | Precision: 0.64 | Recall: 0.27 | F1: 0.38
Threshold: 0.35 | Precision: 0.74 | Recall: 0.20 | F1: 0.31
Threshold: 0.40 | Precision: 0.80 | Recall: 0.14 | F1: 0.24
Threshold: 0.45 | Precision: 0.86 | Recall: 0.12 | F1: 0.21
Threshold: 0.50 | Precision: 0.92 | Recall: 0.09 | F1: 0.16

In [45]:
rf_importances = pd.Series(
    rf_model.feature_importances_,
    index=X_encoded.columns
)

print(rf_importances.sort_values(ascending=False).head(10))

m6_daily_avg_bal             0.022131
m4_daily_avg_bal             0.021927
m5_daily_avg_bal             0.020630
m2_daily_avg_bal             0.019665
m3_daily_avg_bal             0.019151
m1_daily_avg_bal             0.019037
m2_deposit_total_value       0.014940
m3_deposit_total_value       0.013713
m1_deposit_total_value       0.013249
m3_deposit_highest_amount    0.012194
dtype: float64

In [46]:
rf_train_prob = rf_model.predict_proba(X_train)[:, 1]

rf_train_auc = roc_auc_score(y_train, rf_train_prob)

print("Random Forest Training ROC-AUC:", rf_train_auc)
print("Random Forest Validation ROC-AUC:", rf_roc_auc)

Random Forest Training ROC-AUC: 1.0
Random Forest Validation ROC-AUC: 0.7812919730392157

In [47]:
rf_model_v2 = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_model_v2.fit(X_train, y_train)

print("Random Forest v2 training completed!")

Random Forest v2 training completed!

In [48]:
rf_v2_pred_prob = rf_model_v2.predict_proba(X_val)[:, 1]

rf_v2_roc_auc = roc_auc_score(y_val, rf_v2_pred_prob)

print("Random Forest v2 Validation ROC-AUC:", rf_v2_roc_auc)

Random Forest v2 Validation ROC-AUC: 0.7908738970588236

In [49]:
rf_v2_train_prob = rf_model_v2.predict_proba(X_train)[:, 1]

rf_v2_train_auc = roc_auc_score(y_train, rf_v2_train_prob)

print("Random Forest v2 Training ROC-AUC:", rf_v2_train_auc)
print("Random Forest v2 Validation ROC-AUC:", rf_v2_roc_auc)

Random Forest v2 Training ROC-AUC: 0.9948234604779411
Random Forest v2 Validation ROC-AUC: 0.7908738970588236

In [50]:
rf_model_v3 = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_model_v3.fit(X_train, y_train)

print("Random Forest v3 training completed!")

Random Forest v3 training completed!

In [51]:
rf_v3_pred_prob = rf_model_v3.predict_proba(X_val)[:, 1]

rf_v3_roc_auc = roc_auc_score(y_val, rf_v3_pred_prob)

print("Random Forest v3 Validation ROC-AUC:", rf_v3_roc_auc)

Random Forest v3 Validation ROC-AUC: 0.7712789215686273

In [52]:
rf_v2_pred_label = (rf_v2_pred_prob >= 0.5).astype(int)

print(classification_report(y_val, rf_v2_pred_label))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      6800
           1       0.60      0.27      0.38      1200

    accuracy                           0.86      8000
   macro avg       0.74      0.62      0.65      8000
weighted avg       0.84      0.86      0.84      8000

In [53]:
from sklearn.metrics import precision_score, recall_score, f1_score

thresholds = [0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]

for threshold in thresholds:
    pred = (rf_v2_pred_prob >= threshold).astype(int)

    precision = precision_score(y_val, pred)
    recall = recall_score(y_val, pred)
    f1 = f1_score(y_val, pred)

    print(
        f"Threshold: {threshold:.2f} | "
        f"Precision: {precision:.2f} | "
        f"Recall: {recall:.2f} | "
        f"F1: {f1:.2f}"
    )

Threshold: 0.10 | Precision: 0.15 | Recall: 1.00 | F1: 0.26
Threshold: 0.15 | Precision: 0.16 | Recall: 1.00 | F1: 0.28
Threshold: 0.20 | Precision: 0.19 | Recall: 0.97 | F1: 0.32
Threshold: 0.25 | Precision: 0.24 | Recall: 0.86 | F1: 0.37
Threshold: 0.30 | Precision: 0.30 | Recall: 0.70 | F1: 0.42
Threshold: 0.35 | Precision: 0.38 | Recall: 0.55 | F1: 0.45
Threshold: 0.40 | Precision: 0.46 | Recall: 0.43 | F1: 0.44
Threshold: 0.45 | Precision: 0.53 | Recall: 0.34 | F1: 0.42
Threshold: 0.50 | Precision: 0.60 | Recall: 0.27 | F1: 0.38

In [54]:
rf_v2_train_prob = rf_model_v2.predict_proba(X_train)[:, 1]

rf_v2_train_auc = roc_auc_score(y_train, rf_v2_train_prob)

print("Random Forest v2 Training ROC-AUC:", rf_v2_train_auc)
print("Random Forest v2 Validation ROC-AUC:", rf_v2_roc_auc)

Random Forest v2 Training ROC-AUC: 0.9948234604779411
Random Forest v2 Validation ROC-AUC: 0.7908738970588236

In [55]:
final_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

final_model.fit(X_encoded, y)

print("Final model training completed!")

Final model training completed!

In [56]:
test_raw = test[feature_cols].copy()

test_encoded = pd.get_dummies(
    test_raw,
    columns=cat_cols,
    drop_first=True
)

test_encoded = test_encoded.reindex(
    columns=X_encoded.columns,
    fill_value=0
)

print("test_encoded created successfully!")
print("Test shape:", test_encoded.shape)

test_encoded created successfully!
Test shape: (30000, 189)

In [57]:
test_predictions = final_model.predict_proba(test_encoded)[:, 1]

print("Predictions generated!")
print("Number of predictions:", len(test_predictions))
print("First 10 predictions:", test_predictions[:10])

Predictions generated!
Number of predictions: 30000
First 10 predictions: [0.1494881  0.18382536 0.19825556 0.13583637 0.12420658 0.35579428
 0.24378393 0.40537189 0.42063257 0.20578531]

In [58]:
submission = pd.DataFrame({
    "ID": test["ID"],
    "Target": test_predictions
})

print("Submission shape:", submission.shape)
print(submission.head())

Submission shape: (30000, 2)
              ID    Target
0  ID_ED91AC7A28  0.149488
1  ID_29975A9C7E  0.183825
2  ID_F59CE25650  0.198256
3  ID_E875F68D1A  0.135836
4  ID_2902B1C0D0  0.124207

In [59]:
submission.to_csv("submission.csv", index=False)

print("submission.csv saved successfully!")

submission.csv saved successfully!

In [60]:
print("Shape:", submission.shape)
print("Columns:", submission.columns.tolist())
print("Missing values:")
print(submission.isnull().sum())
print("\nTarget range:")
print(submission["Target"].min(), "to", submission["Target"].max())

Shape: (30000, 2)
Columns: ['ID', 'Target']
Missing values:
ID        0
Target    0
dtype: int64

Target range:
0.05911935262762438 to 0.9361418558813781

In [61]:
from sklearn.metrics import log_loss

# Get probability predictions for the validation set
val_predictions = rf_model_v2.predict_proba(X_val)[:, 1]

# Calculate Log Loss
validation_logloss = log_loss(y_val, val_predictions)

print("Validation Log Loss:", validation_logloss)

Validation Log Loss: 0.4143672105693969

In [62]:
print(submission.columns.tolist())

['ID', 'Target']

In [66]:
from sklearn.metrics import log_loss, roc_auc_score

# Baseline: predict the training positive rate for everyone
baseline_prob = y_train.mean()

baseline_predictions = np.full(
    len(y_val),
    baseline_prob
)

baseline_logloss = log_loss(y_val, baseline_predictions)
baseline_auc = roc_auc_score(y_val, baseline_predictions)

print("Baseline probability:", baseline_prob)
print("Baseline Log Loss:", baseline_logloss)
print("Baseline ROC-AUC:", baseline_auc)

print("\nRandom Forest:")
print("Log Loss:", validation_logloss)
print("ROC-AUC:", roc_auc_score(y_val, val_predictions))

Baseline probability: 0.15
Baseline Log Loss: 0.42270908780599104
Baseline ROC-AUC: 0.5

Random Forest:
Log Loss: 0.4143672105693969
ROC-AUC: 0.7908738970588236

In [67]:
print("Validation prediction statistics:")
print(pd.Series(val_predictions).describe())

print("\nSelected percentiles:")
print(
    np.percentile(
        val_predictions,
        [0, 1, 5, 10, 25, 50, 75, 90, 95, 99, 100]
    )
)

Validation prediction statistics:
count    8000.000000
mean        0.286836
std         0.123707
min         0.065503
25%         0.204561
50%         0.259216
75%         0.335251
max         0.930502
dtype: float64

Selected percentiles:
[0.06550283 0.11113028 0.14280508 0.1638597  0.20456073 0.2592161
 0.33525094 0.44747508 0.53642517 0.71771968 0.93050154]

In [68]:
from sklearn.calibration import calibration_curve

prob_true, prob_pred = calibration_curve(
    y_val,
    val_predictions,
    n_bins=10,
    strategy="quantile"
)

print("Mean predicted probability per bin:")
print(prob_pred)

print("\nActual positive rate per bin:")
print(prob_true)

Mean predicted probability per bin:
[0.13876159 0.17912698 0.20435588 0.22627611 0.24810088 0.27088189
 0.29924244 0.33695428 0.39571363 0.56894679]

Actual positive rate per bin:
[0.01125 0.025   0.05    0.06875 0.0975  0.11    0.155   0.2     0.2625
 0.52   ]

In [70]:
from sklearn.model_selection import train_test_split

X_train_model, X_calib, y_train_model, y_calib = train_test_split(
    X_train,
    y_train,
    test_size=0.25,
    random_state=42,
    stratify=y_train
)

print("Model training:", X_train_model.shape)
print("Calibration:", X_calib.shape)
print("Final validation:", X_val.shape)

Model training: (24000, 189)
Calibration: (8000, 189)
Final validation: (8000, 189)

In [71]:
from sklearn.ensemble import RandomForestClassifier

rf_calibration_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_calibration_model.fit(
    X_train_model,
    y_train_model
)

print("Random Forest training completed.")

Random Forest training completed.

In [72]:
from sklearn.calibration import CalibratedClassifierCV

calibrated_rf = CalibratedClassifierCV(
    rf_calibration_model,
    method="sigmoid",
    cv=5
)

calibrated_rf.fit(X_calib, y_calib)

print("Calibration completed.")

Calibration completed.

In [73]:
from sklearn.metrics import log_loss, roc_auc_score

calibrated_predictions = calibrated_rf.predict_proba(X_val)[:, 1]

calibrated_logloss = log_loss(
    y_val,
    calibrated_predictions
)

calibrated_auc = roc_auc_score(
    y_val,
    calibrated_predictions
)

print("Calibrated Random Forest")
print("Log Loss:", calibrated_logloss)
print("ROC-AUC:", calibrated_auc)

Calibrated Random Forest
Log Loss: 0.36594888186024377
ROC-AUC: 0.7579267156862746

In [74]:
from sklearn.metrics import log_loss, roc_auc_score

# Original RF v2 predictions
rf_v2_predictions = rf_model_v2.predict_proba(X_val)[:, 1]

rf_v2_logloss = log_loss(y_val, rf_v2_predictions)
rf_v2_auc = roc_auc_score(y_val, rf_v2_predictions)

# Calibrated RF predictions
calibrated_logloss = log_loss(y_val, calibrated_predictions)
calibrated_auc = roc_auc_score(y_val, calibrated_predictions)

# Competition-style weighted score
rf_v2_score = (
    0.60 * rf_v2_logloss +
    0.40 * (1 - rf_v2_auc)
)

calibrated_score = (
    0.60 * calibrated_logloss +
    0.40 * (1 - calibrated_auc)
)

print("RF v2")
print("Log Loss:", rf_v2_logloss)
print("ROC-AUC:", rf_v2_auc)
print("Combined score:", rf_v2_score)

print("\nCalibrated RF")
print("Log Loss:", calibrated_logloss)
print("ROC-AUC:", calibrated_auc)
print("Combined score:", calibrated_score)

RF v2
Log Loss: 0.4143672105693969
ROC-AUC: 0.7908738970588236
Combined score: 0.3322707675181087

Calibrated RF
Log Loss: 0.36594888186024377
ROC-AUC: 0.7579267156862746
Combined score: 0.31639864284163643

In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV

final_rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

final_calibrated_rf = CalibratedClassifierCV(
    final_rf,
    method="sigmoid",
    cv=5
)

final_calibrated_rf.fit(X_encoded, y)

print("Final calibrated Random Forest trained.")

Final calibrated Random Forest trained.

In [76]:
final_test_predictions = final_calibrated_rf.predict_proba(
    test_encoded
)[:, 1]

print("Number of predictions:", len(final_test_predictions))
print("Minimum probability:", final_test_predictions.min())
print("Maximum probability:", final_test_predictions.max())
print("Mean probability:", final_test_predictions.mean())

Number of predictions: 30000
Minimum probability: 0.019723926487191786
Maximum probability: 0.9691186153911204
Mean probability: 0.1526296912076518

In [77]:
calibrated_submission = pd.DataFrame({
    "ID": test["ID"],
    "Target": final_test_predictions
})

calibrated_submission.to_csv(
    "submission_calibrated.csv",
    index=False
)

print("Submission created successfully.")
print("Shape:", calibrated_submission.shape)
print("Columns:", calibrated_submission.columns.tolist())
print("\nFirst 5 rows:")
print(calibrated_submission.head())

Submission created successfully.
Shape: (30000, 2)
Columns: ['ID', 'Target']

First 5 rows:
              ID    Target
0  ID_ED91AC7A28  0.040355
1  ID_29975A9C7E  0.051628
2  ID_F59CE25650  0.058628
3  ID_E875F68D1A  0.030023
4  ID_2902B1C0D0  0.037041

In [78]:
print("Shape:", calibrated_submission.shape)
print("Columns:", calibrated_submission.columns.tolist())

print("Missing values:")
print(calibrated_submission.isnull().sum())

print("\nDuplicate IDs:", calibrated_submission["ID"].duplicated().sum())

print("\nTarget range:")
print("Minimum:", calibrated_submission["Target"].min())
print("Maximum:", calibrated_submission["Target"].max())

print("\nNumber of probabilities outside [0, 1]:")
print(
    ((calibrated_submission["Target"] < 0) |
     (calibrated_submission["Target"] > 1)).sum()
)

Shape: (30000, 2)
Columns: ['ID', 'Target']
Missing values:
ID        0
Target    0
dtype: int64

Duplicate IDs: 0

Target range:
Minimum: 0.019723926487191786
Maximum: 0.9691186153911204

Number of probabilities outside [0, 1]:
0