In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
train = pd.read_csv("D:/DATASETS/FINANCIAL STRESS PREDICTOR/train.csv")
test = pd.read_csv("D:/DATASETS/FINANCIAL STRESS PREDICTOR/test.csv")

In [3]:
train.head()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal,liquidity_stress_next_30d,ID
0,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,8,58372.55,...,0.00,0.0,12488.72,11404.86,12943.70,14157.61,13202.11,4336.98,1,ID_C1DF84C4D2
1,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,5191.14,4.0,13677.61,2781.25,5897.59,5416.23,11062.23,4849.68,0,ID_CB8B764D76
2,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,12,41262.86,...,0.00,0.0,7271.09,5364.41,9023.13,13001.02,17107.92,15174.32,1,ID_D40D58FC67
3,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,10,8738.58,...,8965.63,3.0,14331.10,33465.26,2973.45,3577.07,18990.91,8488.26,0,ID_CFD8F26581
4,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,2,3654.68,...,0.00,0.0,5602.75,8497.49,26252.75,7618.93,9290.65,4214.71,0,ID_20EB501231

In [4]:
test.head()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_total_value,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal,ID
0,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,0.00,0.00,0.0,7272.55,9390.57,17239.77,12989.74,11233.97,16461.21,ID_ED91AC7A28
1,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,14,89420.67,...,99816.47,11869.21,2.0,9541.97,2966.31,8673.89,11626.41,4163.57,4978.28,ID_29975A9C7E
2,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,27491.22,7761.80,5.0,3182.31,10784.62,5614.67,6834.96,10062.58,2954.87,ID_F59CE25650
3,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,0,0.00,...,25776.34,13914.75,3.0,15452.29,32939.01,3682.57,8570.83,8688.00,9627.55,ID_E875F68D1A
4,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,0,0.00,...,57119.91,12371.51,5.0,11052.63,7294.56,32332.63,4043.43,11680.77,7326.46,ID_2902B1C0D0

In [5]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Columns: 184 entries, arpu to ID
dtypes: float64(134), int64(44), str(6)
memory usage: 56.2 MB

In [6]:
train.isnull()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal,liquidity_stress_next_30d,ID
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
train.isnull().sum()

arpu                         0
age                          0
gender                       0
region                       0
smartphone                   0
                            ..
m4_daily_avg_bal             0
m5_daily_avg_bal             0
m6_daily_avg_bal             0
liquidity_stress_next_30d    0
ID                           0
Length: 184, dtype: int64

In [8]:
train.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
39995    False
39996    False
39997    False
39998    False
39999    False
Length: 40000, dtype: bool

In [9]:
train.duplicated().sum()

np.int64(0)

In [10]:
train["liquidity_stress_next_30d"].value_counts()

liquidity_stress_next_30d
0    34000
1     6000
Name: count, dtype: int64

In [11]:
train["liquidity_stress_next_30d"].value_counts(normalize=True) * 100

liquidity_stress_next_30d
0    85.0
1    15.0
Name: proportion, dtype: float64

In [12]:
TARGET = "liquidity_stress_next_30d"
y = train[TARGET]
y.head()

0    1
1    0
2    1
3    0
4    0
Name: liquidity_stress_next_30d, dtype: int64

In [13]:
y.dtype, y.nunique()

(dtype('int64'), 2)

In [14]:
y.value_counts()

liquidity_stress_next_30d
0    34000
1     6000
Name: count, dtype: int64

In [15]:
ID_COL = "ID"

feature_cols = [
    c for c in train.columns
    if c not in [ID_COL, TARGET]
]

print("Number of features:", len(feature_cols))

Number of features: 182

In [16]:
X = train[feature_cols]

X.head()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_volume,m6_withdraw_total_value,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal
0,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,8,58372.55,...,0,0.00,0.00,0.0,12488.72,11404.86,12943.70,14157.61,13202.11,4336.98
1,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,9,90423.40,5191.14,4.0,13677.61,2781.25,5897.59,5416.23,11062.23,4849.68
2,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,12,41262.86,...,0,0.00,0.00,0.0,7271.09,5364.41,9023.13,13001.02,17107.92,15174.32
3,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,10,8738.58,...,11,98268.75,8965.63,3.0,14331.10,33465.26,2973.45,3577.07,18990.91,8488.26
4,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,2,3654.68,...,0,0.00,0.00,0.0,5602.75,8497.49,26252.75,7618.93,9290.65,4214.71

In [17]:
cat_cols = X.select_dtypes(include="object").columns.tolist()

print("Number of categorical features:", len(cat_cols))
print(cat_cols)

Number of categorical features: 5
['gender', 'region', 'smartphone', 'segment', 'earning_pattern']

C:\Users\Eis7\AppData\Local\Temp\ipykernel_15016\1261099881.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include="object").columns.tolist()

In [18]:
for col in cat_cols:
    print(f"\n{col}:")
    print(X[col].unique())

gender:
<StringArray>
['F', 'M']
Length: 2, dtype: str

region:
<StringArray>
[              'Central Zone',         'Northern Highlands',
      'Lake Zone (Northwest)', 'Coastal & Eastern Corridor',
         'Southern Highlands',                   'Islander',
               'Western Zone']
Length: 7, dtype: str

smartphone:
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

segment:
<StringArray>
['MVC', 'LVC', 'HVC']
Length: 3, dtype: str

earning_pattern:
<StringArray>
['Monthly Earner', 'Weekly Earner', 'Irregular Earner']
Length: 3, dtype: str

In [19]:
X_encoded = X.copy()

X_encoded.head()

,arpu,age,gender,region,smartphone,segment,earning_pattern,x_90_d_activity_rate,m1_paybill_volume,m1_paybill_total_value,...,m6_withdraw_volume,m6_withdraw_total_value,m6_withdraw_highest_amount,m6_withdraw_agents,m1_daily_avg_bal,m2_daily_avg_bal,m3_daily_avg_bal,m4_daily_avg_bal,m5_daily_avg_bal,m6_daily_avg_bal
0,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,8,58372.55,...,0,0.00,0.00,0.0,12488.72,11404.86,12943.70,14157.61,13202.11,4336.98
1,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,0,0.00,...,9,90423.40,5191.14,4.0,13677.61,2781.25,5897.59,5416.23,11062.23,4849.68
2,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,12,41262.86,...,0,0.00,0.00,0.0,7271.09,5364.41,9023.13,13001.02,17107.92,15174.32
3,2653.88,47,F,Central Zone,Yes,MVC,Monthly Earner,0.6905,10,8738.58,...,11,98268.75,8965.63,3.0,14331.10,33465.26,2973.45,3577.07,18990.91,8488.26
4,20535.82,63,F,Northern Highlands,No,MVC,Weekly Earner,0.8959,2,3654.68,...,0,0.00,0.00,0.0,5602.75,8497.49,26252.75,7618.93,9290.65,4214.71

In [20]:
X_encoded = pd.get_dummies(
    X_encoded,
    columns=cat_cols,
    drop_first=True
)

print("Features after encoding:", X_encoded.shape[1])

Features after encoding: 189

In [21]:
X_encoded.dtypes.value_counts()

float64    134
int64       43
bool        12
Name: count, dtype: int64

In [22]:
X_encoded.isnull().sum().sum()

np.int64(0)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("y_train:", y_train.shape)
print("y_val:", y_val.shape)

X_train: (32000, 189)
X_val: (8000, 189)
y_train: (32000,)
y_val: (8000,)

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

print("X_train_scaled:", X_train_scaled.shape)
print("X_val_scaled:", X_val_scaled.shape)

X_train_scaled: (32000, 189)
X_val_scaled: (8000, 189)

In [25]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=100,
    class_weight="balanced",
    solver="liblinear"
)

model.fit(X_train_scaled, y_train)

print("Model training completed!")

Model training completed!

In [26]:
val_pred_prob = model.predict_proba(X_val_scaled)[:, 1]

print(val_pred_prob[:10])

[0.37989242 0.05355732 0.77078879 0.44734794 0.52814447 0.36998911
 0.10859922 0.70464795 0.48004258 0.69307449]

In [27]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_val, val_pred_prob)

print("Validation ROC-AUC:", roc_auc)

Validation ROC-AUC: 0.7531676470588237

In [28]:
val_pred_label = (val_pred_prob >= 0.5).astype(int)

print(val_pred_label[:20])

[0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 0]

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_val, val_pred_label))

              precision    recall  f1-score   support

           0       0.93      0.69      0.79      6800
           1       0.28      0.70      0.40      1200

    accuracy                           0.69      8000
   macro avg       0.61      0.69      0.60      8000
weighted avg       0.83      0.69      0.73      8000

In [30]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_val, val_pred_label)

print(cm)

[[4680 2120]
 [ 360  840]]

In [31]:
from sklearn.inspection import permutation_importance

In [32]:
result = permutation_importance(
    model,
    X_val_scaled,
    y_val,
    n_repeats=3,
    random_state=42,
    n_jobs=-1
)

print("Permutation importance completed!")

Permutation importance completed!

In [33]:
importances = pd.Series(
    result.importances_mean,
    index=X_encoded.columns
)

print(importances.sort_values(ascending=False).head(10))

m5_daily_avg_bal              0.041167
m4_daily_avg_bal              0.040708
m6_daily_avg_bal              0.040375
segment_MVC                   0.028958
m2_withdraw_volume            0.018167
m1_withdraw_volume            0.017833
m3_withdraw_volume            0.017667
m1_received_highest_amount    0.014375
m6_deposit_volume             0.012167
m3_mm_send_volume             0.011667
dtype: float64